config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/", to: "home#index"
  get "/profile/:id", to: "profile#index", as: 'profile'
  #get '/profile/:id/edit/', to: "profile#edit", as: "profile_edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  validates :username, presence: true
  validates :role, presence: true, inclusion: {  in: %w[admin employee] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :username, :role])
    devise_parameter_sanitizer.permit(:account_update, keys: [:email, :username, :role, :avatar])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  def index
    @user = User.find(params[:id])
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<div class="container">
    <%= render partial: "partials/nav" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700;800&display=swap" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
  </body>
</html>

app/views/partials/_nav.html.erb
<%= stylesheet_link_tag "header.css" %>

<div class="container">
    <div class="header">
        <div class="logo">
            <a href="">
                <%= image_tag "logo.png", class:"logo_image" %>
            </a>
        </div>
        <div class="header_menu">
            <p>Item</p>
            <p>Item</p>
            <p>Item</p>

        </div>
        <div class="header_admin_panel">
            <% if user_signed_in? %>
                <%= button_to "Sign out", destroy_user_session_path, :method => :delete, class:"button button_primary button_primary_danger" %>
                <a href="<%= profile_path(current_user.id) %>"><%= image_tag "user.png", class:"icon_link" %></a>
            <% else %>
                <%= link_to "Sign up", new_user_registration_path, class:"button button_primary" %>
                <%= link_to "Sign in", new_user_session_path, class:"button button_primary" %>
            <% end %>
        </div>
        <% if current_user.role == "admin" %>
            <p class="show_user_role role_admin">Admin panel</p>
        <% else %>
            <p class="show_user_role role_employee">Employee panel</p>
        <% end %>
    </div>
</div>